### ISSUE TITLE
attention weights 

### ISSUE THREAD

**Issue by nkooli** [Humanity123/MemNet_ABSA#1]
how can we see attention weights in different hops like shown in table 4 and table 5 in the paper https://arxiv.org/pdf/1605.08900.pdf

Thank you

**Comment by Humanity123** [comment]
You can view it using the self.P tensor. self.P tensor denotes the attention weights given to the context words. If you want to print the attention weights at each hop you can change the model slightly and append the attention weights to a list  after each hop. You can even use tf.Print which would then print the weights after each hop.

**Comment by nkooli** [comment]
@Humanity123 thank you for your response

i don't see where to add tf.Print(self.P, [self.P]), can you explain more please?

**Comment by Humanity123** [comment]
@nkooli 
May be this would help.

TensorfFlow Link - https://www.tensorflow.org/api_docs/python/tf/Print
StackOverflow Link - https://stackoverflow.com/questions/47000828/how-to-print-part-of-a-tensor-using-tf-print

Add this line after the line where self.P is computed
self.P = tf.Print(self.P, [self.P],  "Print Attention For Batch-\n")

Look at the summarize argument in tf.Print to print the appropriate number of entries/ values from the attention (self.P) tensor.

**Comment by nkooli** [comment]
i'm sorry to bother you, but this print something like this :

`2018-03-14 18:00:13.154329: I tensorflow/core/kernels/logging_ops.cc:79] Print Attention For Batch- n[[0.0019893979 0.0019721095 0.0019720972 0.014456456 0.0019809948 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009 0.001975009]...]
`

and i am not able to interpret and match with tables in the paper. Any idea?
